Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-8.6"

  config.vm.synced_folder '.', disabled: true
  config.vm.synced_folder '../..', '/vagrant', type: 'rsync', rsync__exclude: ['target', 'testing']

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.host_vars = {
      "building" => {"nginx_port" => 2003 },
      "testing" => {"nginx_port" => 2004 }
    }
  end

  config.vm.define "building" do |building|
    building.vm.network "forwarded_port", guest: 2003, host: 2003
  end

  config.vm.define "testing" do |testing|
    testing.vm.network "forwarded_port", guest: 2004, host: 2004
  end
end
