version: '3.2'
services:
  tests:
    build: .
    depends_on:
      - nginx
      - btb
  nginx:
    image: "nginx"
    ports:
     - "8080:8080"
    volumes:
      - type: bind
        source: ./nginx/private
        target: /usr/share/nginx/html/private
        read_only: true
      - type: bind
        source: ./nginx/default-nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
  btb:
    build: ../..
